services:
  mysql:
    image: mysql:latest
    container_name: desafio_sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rede_social
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
